### ISSUE TITLE
Create placeholder landing page

### ISSUE THREAD

**Issue by WouterJanson** [WouterJanson/echteerlijkegeldwijzer.nl#1]
A quick and simple landing page, So visiters won’t see the current TransIP placeholder before the site is live.

**Comment by D-on-GitHub** [comment]
I will add a random coming soon page I saved on my local disk, okay?

**Comment by WouterJanson** [comment]
Go ahead, everything is better than the current TransIP one 👍

**Comment by D-on-GitHub** [comment]
Commit done

**Comment by WouterJanson** [comment]
Will upload to host later tonight.

Done!
