### ISSUE TITLE
When resizing the browser the title row of the table doesn't line up

### ISSUE THREAD

**Issue by helmerzNL** [WouterJanson/echteerlijkegeldwijzer.nl#13]
![eerlijkegeldwijzer-resize](https://user-images.githubusercontent.com/658834/37572495-191b2594-2b0c-11e8-9672-4abee7146cf3.png)

**Comment by WouterJanson** [comment]
Can't reproduce on:
`Microsoft Edge 41.16299.248.0`
`Microsoft EdgeHTML 16.16299`

**Comment by WouterJanson** [comment]
Issue with preview version of Edge.
Closed for now
