### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by WouterJanson** [WouterJanson/echteerlijkegeldwijzer.nl#2]
I believe @JohnDoNL was already working on a logo

**Comment by JohnDoNL** [comment]
Yes, I am :)

**Comment by JohnDoNL** [comment]
![echteerlijkegeldwijzer_logo](https://user-images.githubusercontent.com/37486074/37567586-6e3ebcb8-2ac9-11e8-9c0d-07791e81bbf8.png)
