### ISSUE TITLE
Figure out bunq rating/report

### ISSUE THREAD

**Issue by WouterJanson** [WouterJanson/echteerlijkegeldwijzer.nl#3]
The whole point of this site is to add bunq to the comparison of eerlijkegeldwijzer.nl, but how are we going to rate bunq?

**Comment by D-on-GitHub** [comment]
Maybe we can add a note that bunq does not invest, so that there are no scores to show.

**Comment by WouterJanson** [comment]
We can use the remarks section in the yaml to add that.
We also could show the 0 as Nvt.

The remarks tooltip #5 isn't created yet though.

**Comment by D-on-GitHub** [comment]
I think that is a good idea, because other banks also don't have scores on all categories.

**Comment by WouterJanson** [comment]
Needs to be revised.
`Gendergelijkheid` for example isn't about investing

**Comment by WouterJanson** [comment]
I've asked Bianca from bunq for some input

**Comment by WouterJanson** [comment]
> Gendergelijkheid:
Wij hebben gelijke beloning voor mannen en vrouwen met vergelijkbare functies en werkervaring. Man/vrouw verhouding = 65%/35%

> Arbeidsrechten:
We hebben ons kantoor ingericht zodat mensen op een veilige en gezonde manier kunnen werken (gedocumenteerd in een RI&E). Wat betreft beloning voeren wij regelmatig salarisbenchmarks uit om een vergelijking te maken met andere startups en een eerlijk beloningsbeleid uit te voeren. Onze voorzieningen krijgen van ons extra aandacht om iedereen te faciliteren. Zo hebben we iedere dag een lunch die wordt bereid door onze kok en hebben we iedere avond koks die voor ons koken (waar mensen zich voor het eten kunnen aanmelden).
Collectieve onderhandelingen zijn bij ons niet van toepassing omdat wij niet tot een CAO behoren. We hebben daarnaast geen bonussen. Enkel 8% vakantiegeld wat wettelijk is vastgelegd in Nederland. 


> Corruptie:
We hebben een heldere policy op conflicts of interests en accepting gifts (max 100 EUR op jaarbasis, alles daarboven moet worden gemeld of goedgekeurd). Uiteraard ondersteunen we daarnaast niet opzettelijk bij het witwassen van geld of het betalen van steekpenningen. 


> Belastingen: 
Wij zijn transparant over onze eigen belasting betalingen, dit is ook vrij eenvoudig, omdat we alleen in Nederland zijn gevestigd. We verlenen daarnaast geen financiele diensten aan bedrijven/particulieren die zich structureel schuldig maken aan belastingontduiking. We accepteren alleen EU citizens en vragen belastingnummers op van alle users (wat elke bank wettelijk verplicht is), we hebben daarnaast een risk policy voor ingewikkelde corporate structures.

- Bianca

**Comment by petervdv** [comment]
Close this issue again?
